sheerun/vim-polyglot

README.md
build

The current Swift package hasn't been updated in a year, lacks Swift 2.0 support, has incorrect syntax highlighting, and has glitchy indentation. https://github.com/keith/swift.vim seems to work better and is still maintained.

Use updated Swift plugin

---

README.md
build

[old repo](https://github.com/wting/rust.vim) was moved to [rust-lang group](https://github.com/rust-lang/rust.vim) few months ago.

rust repository url updated

---

README.md

SVG badge are lighter and have a nicer rendering, expecially on retina display.

Use SVG for travis badge

---

build

`ftdetect/polyglot.vim`
Before
```vim
if !exists('foo')
" foo ftdetect content
endif
if !exists('bar')
" bar ftdetect content
endif
```
After
```vim
" ftdetect/foo.vim
if !exists('foo')
" foo ftdetect content
endif
" ftdetect/bar.vim
if !exists('bar')
" bar ftdetect content
endif
```

readability: add newline and comment to generated ftdetect file

---

spec/loading_spec.rb

There's been several PRs that inexplicably failed tests.
PR #279 (applescript) failed with "should parse test.em file" despite
the exact same PR #286 passing (I've removed one of them, sorry again
about that).
PR #268 (pandoc) failed with "parse test.erb file" but doesn't mess with
eruby.
PR #281 (readme) failed with "should parse test.jsx file" but it's a one
word change to the readme!
My assumption is that vim startup on Travis is near the edge of the
timeout so we're getting false failures. (I'm not familiar with
Vimrunner or rspec, but I assume this code is just testing that vim
doesn't throw errors one edit and automatically exits at the end of the
block.)

Increase test file parsing timeout

---

build

Rounds off some poke-y edges, makes things a bit more predictable (especially in terms of handling filenames with embedded whitespace), and eliminates all complaints from https://github.com/koalaman/shellcheck .
PR rather than direct commit to master because I want to make sure that, as it is on my machine, the output of these changes is exactly equal to the old `build` when run on @sheerun's machine.

Cleanup `build` syntax a bit, aided by `shellcheck(1)`

---

build

Current applescript defines a syntax file, but doesn't setup an
applescript filetype to apply the syntax.
This one does ftdetect, indent, and has some ftplugin for running
applescript through osascript.
It uses an identical syntax file to the existing one.

Update applescript to one that provides ftdetect

---

build

Extremely simple PR here. 
All this does is sets the system's locale to `C` explicitly so that the sort function will sort the readme the exact same way on all systems.
Let me know if you have any questions....

[build] explicitly set locale to C when sorting

---

.travis.yml
spec/loading_spec.rb
spec/spec_helper.rb

Fixes #380 
The key change here is restarting vim server for every file.
I also added execution of `build` script to be able to check PRs.
I tried different approaches: pure bash, vimrunner in python. They work pretty fast in comparison with the ruby version. Apart from that, I noticed that test actually doesn't check anything. If a *.vim file is corrupted, no error messages are displayed.

FIx CI build freezing

---

README.md

I noticed that during [`ftdetect/polyglot.vim`](https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim#L574), the variable `g:polyglot_disabled` wasn't defined, even it's already declared in my `.vimrc`.
I'm not sure putting `g:polyglot_disabled` before polyglot load is a good practice, but if it's necessary, we should probably add some docs on this.

headsup on g:polyglot_disabled

---

build

When I run `build` on my machine, I end up with hunks of moved code in `ftdetect/polyglot.vim`. For example,
```bash
diff -U1 \
<( git show v4.2.0:ftdetect/polyglot.vim | grep -F ', from' ) \
<( grep -F ', from' ftdetect/polyglot.vim )
```
```diff
@@ -19,9 +19,9 @@
" dhall, from dhall.vim in vmchale/dhall-vim
-  " dlang, from d.vim in JesseKPhillips/d.vim
" dlang, from dcov.vim in JesseKPhillips/d.vim
-  " dlang, from dd.vim in JesseKPhillips/d.vim
" dlang, from ddoc.vim in JesseKPhillips/d.vim
+  " dlang, from dd.vim in JesseKPhillips/d.vim
" dlang, from dsdl.vim in JesseKPhillips/d.vim
-  " dockerfile, from Dockerfile.vim in ekalinin/Dockerfile.vim
+  " dlang, from d.vim in JesseKPhillips/d.vim
" dockerfile, from docker-compose.vim in ekalinin/Dockerfile.vim
+  " dockerfile, from …
```

Combine ftdetect files in a predictable order

---

ftdetect/polyglot.vim

Commit f3804b0892e17f309f852696491096d9048f0ef8 disabled TypeScript for .ts files.
This change restores the previous configuration.

Enable TypeScript in ftdetect

---

ftdetect/polyglot.vim

Standard convention for rspec files is "*_spec.rb". This is also what
rspec.vim (the syntax plugin that is pulled in) uses.

add detection for rspec files

---

scripts/build

@sheerun It looks like some missing newlines were breaking ftdetect for mako templates. This PR adds them.
On a related note, the outer filetype doesn't seem to be getting detected when the extension is simply `.mako` like it had previously. I'll poke around and see if I can figure out why that is.

add missing newlines

---

ftdetect/polyglot.vim
scripts/build

Without the period, the autocommand for extensions like `.html.mako` was firing for `.mako` files. Filling it in fixes detection for `.mako` files.
The fancy detection for extensions like `.html.mako` seems to still be broken, but judging by the E201, I think it's also broken for the upstream mako plugin. I might poke the maintainer and see if we can find a better way to do that detection here soon.

add missing period to fix mako detection

---

autoload/polyglot/shebang.vim

I was making a new script, and during writing the path for shebang, saw this error:
``` vim
Error detected while processing CursorHold Autocommands for "<buffer=1>"..function polyglot#shebang#Detect[1]..<SNR>78_Filetype:
line   15:
E684: list index out of range: -1
```
It's because `split(l:path, "/")` returns an empty list, so this PR fixes it.
This can be reproduced by making a new file and insert the content of the following:
``` text
#!/
```
Then go to NORMAL mode or insert a space to see the error message.

Fix error when editing path for shebang

---

autoload/polyglot/util.vim

On Windows, should handle both slash and backslash as the path separator in checking a path in 'rtp'.

Fix the filter of 'rtp'

---

ftdetect/polyglot.vim

Fixes #619 .
The most straightforward patch to avoid the error I investigated at https://github.com/sheerun/vim-polyglot/issues/619#issuecomment-720512823 .

Restore cpoptions before recursive ftdetect read, fixes #619

---

ftdetect/polyglot.vim

I'm one of the users who don't use `set incsearch` and therefore haven't installed the plugin `tpope/vim-sensible`.
So for me this UI related setting was a surprise and even if I can disable it, I recommend to not copying this behaviour from `vim-sensible`, as long as it is not a requirement for the core functionality of `vim-polyglot` (I would be ok with vim/nvim changing the default so I can easily disable it, but I don't want to overwrite plugins which I don't expect to change an already set option)

Removes `set incsearch` which was copied from vim-sensible

---

autoload/polyglot/init.vim

This is a workaround that replaces array slice with while loops while iterating `rtp`.
Should fix issue https://github.com/sheerun/vim-polyglot/issues/665 that popped up for me also on CentOS/RHEL7 with vim7.4:
```
Error detected while processing function <SNR>13_process_rtp:
line   22:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
line   32:
E117: Unknown function: i:len
E15: Invalid expression: rtp[i:len(rtp)-1]
```
I can't test this on Vim 8 but on 7.4 it now loads just fine.

replace array slice with while loops for Vim 7.4, closes #665

---

README.md

The ekalinin/Dockerfile.vim plugin supports not only docker-compose
files, but also Dockerfile files. Therefore, I think it is more accurate
to say that vim-polyglot supports Docker in general.

Update README to clarify broader Docker support

---

extras/filetype.vim

Fixes #783
This appears to fix the issue for me. Not sure if this is the best way to do it. Happy to rework the PR.
https://github.com/vim/vim/issues/9890 is also helpful for context.

Check if TestFiletypeFuncs exists before defining it

---

autoload/polyglot/init.vim

The doubled comma (,,) in the list of autocmd patterns introduces a
blank pattern which matches all filenames in the most recent version of
neovim, causing the default filetype to be sh unless another rule
overrides it.

Fix doubled comma in autocmd

---

packages.yaml

Add missing filetypes for [go.sum](https://github.com/fatih/vim-go/blob/master/syntax/gosum.vim) and [go.work](https://github.com/fatih/vim-go/blob/master/syntax/gowork.vim) to the `packages.yaml` file
I did run `make build` to confirm it works. But since it created quite a lot of unrelated changes I did not push it into the PR.

Add missing filetypes for go.sum and go.work

---

extras/filetype.vim
scripts/build

Rename `TestFiletypeFuncs` to avoid name collision
